# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 08:57
from __future__ import unicode_literals

import WebAnalyzer.utils.filename
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image', models.ImageField(upload_to=WebAnalyzer.utils.filename.uploaded_date)),
                ('token', models.AutoField(primary_key=True, serialize=False)),
                ('options', models.TextField(default='')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('similarity', models.TextField()),
                ('image', models.TextField()),
                ('name', models.TextField()),
                ('result_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='WebAnalyzer.ImageModel')),
            ],
        ),
    ]
